add the main_ground_data pointer
UsernameFodder/pmdsky-debug pull request #10
Opened 2022-02-25 13:05 UTC by marius851000

That's a pretty simple change, to test a bit the CI (but entered information are valid, at least AFAIK)

2022-02-25 16:24 UTC, UsernameFodder commented
The CI will be a bit annoying on this first PR since you're a first-time contributor and I'll have to approve runs (apparently GitHub does this to prevent cryptomining abuse), but in future PRs it should be easier.

2022-02-25 16:31 UTC, UsernameFodder requested changes

2022-02-25 16:31 UTC, UsernameFodder commented on headers/types/ground_mode/ground_mode.h
> +#include "partner_following.h";
There's no such file. Delete this line?

2022-02-25 16:31 UTC, UsernameFodder commented on headers/types/ground_mode/ground_mode.h
> +}
Semicolon here

2022-02-25 16:31 UTC, UsernameFodder commented on headers/types/ground_mode/ground_mode.h
> +    undefined[]* actors; //0x8: pointer to the actors
I don't think there's much point in making this an array pointer `[]*`. Let's just make it a normal pointer.

2022-02-25 16:31 UTC, UsernameFodder commented on headers/types/ground_mode/ground_mode.h
> +    undefined* script; //0x0: pointer to script structure
Some [formatting issues](https://github.com/UsernameFodder/pmdsky-debug/runs/5336315279?check_suite_focus=true) with the comments. Need a space after the `//`. You can also [download the formatted file](https://github.com/UsernameFodder/pmdsky-debug/actions/runs/1898774927#artifacts) directly.

2022-02-25 16:31 UTC, UsernameFodder commented on headers/types/ground_mode/ground_mode.h
> +// A global structure holding various pointer to important structure
Can we elaborate a bit more? How about "A global structure holding various pointers to important structures for ground mode"?

2022-02-25 16:31 UTC, UsernameFodder commented on symbols/overlay11.yml
> +        type: main_ground_data
`struct main_ground_data`

2022-04-28 06:54 UTC, marius851000 commented
Well, finally applied those change (after having the motivation following the discussion in the new asm channel).

2022-04-28 15:40 UTC, UsernameFodder requested changes

2022-04-28 15:40 UTC, UsernameFodder commented on headers/types/types.h
> -
Can we leave this file as is? There's no need to change anything here.

2022-04-28 15:40 UTC, UsernameFodder commented on headers/types/ground_mode/ground_mode.h
> +    undefined* script; // 0x0: pointer to script structure
The formatter likes comments on struct fields to be aligned; you can just download [the formatted file (under "Artifacts")](https://github.com/UsernameFodder/pmdsky-debug/actions/runs/2237612286#artifacts) and apply it to this PR.

2022-05-06 00:48 UTC, UsernameFodder requested changes
I almost forgot, make sure to add yourself to the top-level `CREDITS.txt` file if you want! 😄

2022-05-06 08:59 UTC, marius851000 commented
For the credit, should I put myself under ``SBDWolf`` or after the other generic credits ?

2022-05-06 09:03 UTC, marius851000 commented
Humm...The formatter did some strange stuff, but hopefully, it should work now.

2022-05-06 15:47 UTC, UsernameFodder commented
> For the credit, should I put myself under `SBDWolf` or after the other generic credits ?

Yep, that's good.

> Humm...The formatter did some strange stuff, but hopefully, it should work now.

Yeah there's a soft column limit, so the formatter opted to wrap the line. Usually I move the comment to the line above in cases like that, but it doesn't matter too much.

2022-05-06 15:47 UTC, UsernameFodder approved these changes
LGTM, thanks!

2022-05-06 15:48 UTC, merged