Added the unknown functions within ApplyTrapEffect and other trap information
UsernameFodder/pmdsky-debug pull request #132
Opened 2023-04-12 05:55 UTC by Jawshoeuh

2023-04-12 15:22 UTC, UsernameFodder requested changes

2023-04-12 15:22 UTC, UsernameFodder commented on symbols/overlay10.yml
> +      description: "The boosed kecleon shop spawn chance multiplier (~1.2) as a binary fixed-point number (8 fraction bits)."
boosted

Also, apparently the formatter wants the quotes to be removed.

2023-04-12 15:22 UTC, UsernameFodder commented on symbols/overlay29.yml
> +    - name: ApplyTripTrapEffect
This one is missing a signature in the headers

2023-04-12 15:32 UTC, UsernameFodder commented
Btw at this point your `master` branch is 30 commits ahead of upstream. Since you're merging upstream/master into your own branch, you can see merge commits in your branch's history, which causes it to look different from upstream, and so each PR is showing all 30 commits from your branch.

I usually solve this by rebasing or fast-forward merging against upstream rather than creating merge commits, but that's maybe harder if you aren't familiar with git. In the future, I would recommend resetting your master branch to exactly match upstream, then creating a separate branch for each new pull request. That way, the master branch can remain in sync with upstream, and you can start fresh on new branches with each new pull request. Let me know if you need help with this.

2023-04-12 15:42 UTC, End45 commented on symbols/overlay29.yml
> +        Spawns several monsters around the position and gives them all the grudge status
Doesn't the trap give the grudge status to all the enemies on the floor?

2023-04-13 04:11 UTC, UsernameFodder approved these changes
LGTM

2023-04-13 04:12 UTC, merged