Add information about the PreprocessString function
UsernameFodder/pmdsky-debug pull request #9
Opened 2022-02-22 21:05 UTC by EleventhNov

2022-02-23 02:04 UTC, UsernameFodder requested changes
Looks good, just a couple syntactical/formatting issues to fix.

2022-02-23 02:04 UTC, UsernameFodder commented on headers/types/common/common.h
> +}
Need a semicolon here

2022-02-23 02:04 UTC, UsernameFodder commented on headers/types/common/common.h
> +}
Semicolon here

2022-02-23 02:04 UTC, UsernameFodder commented on symbols/arm9.yml
> +
Kind of annoying, but with YAML you need to have spaces at the start of empty lines to match the indentation of the paragraphs. Same thing with the other blank line.

2022-02-23 02:44 UTC, EleventhNov commented
Oh boy that's embarrasing lol, I really need to get a syntax checker... Hopefully this fixes it tho!

2022-02-23 03:08 UTC, UsernameFodder commented
> Oh boy that's embarrasing lol, I really need to get a syntax checker... Hopefully this fixes it tho!

It'll be a bit more annoying on this PR since it's your first and GitHub asks me for approval before the automatic checks will run (apparently it was to stop cryptomining abuse! :P). On subsequent PRs you'll be able to use the pipeline results as a syntax checker without needing to worry about setting anything up yourself.

2022-02-23 03:11 UTC, UsernameFodder requested changes

2022-02-23 03:11 UTC, UsernameFodder commented on headers/types/common/common.h
> +ASSERT_SIZE(preprocessor_args, 80);
One more compile issue, use `struct preprocessor_args` here.

2022-02-23 03:11 UTC, UsernameFodder commented on headers/types/common/common.h
> +    // When they're talking through a message box. It requires it's respective flag to be on
Does this comment refer to the above `speaker_id`? If so, could you move the comments to the line above the field? This is the style I've been using:
```c
    // An optional argument that is used to insert the name of a Pokémon.
    // When they're talking through a message box. It requires its respective flag to be on
    uint32_t speaker_id;
```

2022-02-23 03:16 UTC, UsernameFodder requested changes

2022-02-23 03:16 UTC, UsernameFodder commented on headers/functions/arm9.h
> +                     struct preprocessor_flags flags, struct preprocessor_args* args);
[Formatter caught](https://github.com/UsernameFodder/pmdsky-debug/runs/5298100158?check_suite_focus=true) that there's enough room to put `struct preprocessor_flags flags` on the previous line.

2022-02-23 03:16 UTC, UsernameFodder commented on headers/types/common/common.h
> +    int32_t number_vals[5];
[Formatter caught]([Formatter caught](https://github.com/UsernameFodder/pmdsky-debug/runs/5298100158?check_suite_focus=true) that there's enough room to put `struct preprocessor_flags flags` on the previous line.) that there's an extra space at the end of this line :o.

2022-02-23 06:37 UTC, UsernameFodder requested changes

2022-02-23 06:37 UTC, UsernameFodder commented on headers/types/common/common.h
> -#endif
Err, let's keep the empty line at the end of the file as is. It makes things look a little nicer in the GitHub viewer.

2022-02-24 19:39 UTC, EleventhNov commented
Cryptomining abuse huh? That's something I didn't expect to hear here today haha, Anyway I apologize for the clunkiness, Hopefully this fixes it for good

2022-02-24 20:06 UTC, UsernameFodder approved these changes
Looks good now. Thanks for contributing!

2022-02-24 20:06 UTC, merged